version: "3.9"

services:
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/lzw_docker/resume:backend-laste
    ports:
      - "5000:5000"
    volumes:
      - /vol1/1000/docker/resume/backend_uploads:/app/uploads
      - /vol1/1000/docker/resume/backend_db/resume_app.db:/app/resume_app.db
    restart: unless-stopped

  frontend:
    image: registry.cn-hangzhou.aliyuncs.com/lzw_docker/resume:frontend-laste
    ports:
      - "3100:3000"
    environment:
      VITE_BACKEND_URL: http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_uploads:
  backend_db:

